int nb_bonbons = 11;
int nb_personnes = 3;
nb_bonbons ++;
nb_personnes --;
int bonbons_personnes = nb_bonbons / nb_personnes;
int reste = nb_bonbons % nb_personnes;
System.out.println(nb_bonbons);
System.out.println(nb_personnes);
System.out.println(bonbons_personnes);
System.out.println(reste);